docs/PERFORMANCE.md, src/k2/cmd/nodepool/nodepool_main.cpp, src/k2/module/k23si/Config.h, src/k2/module/k23si/Persistence.cpp
Allow multiple persistence endpoints to be passed on the command line. Each core will pick a different persistence endpoint to connect to.
=> Allow multiple persistence endpoints

src/k2/module/k23si/client/k23si_client.cpp, src/k2/module/k23si/client/k23si_client.h
The MTR can be used as a transaction ID when tracking multiple txns
=> Expose the transaction MTR

src/k2/transport/RPCParser.cpp, test/integration/test_3si_txn.sh, test/integration/test_collection.sh, test/integration/test_k23si.sh, test/integration/test_partition.sh, test/integration/test_plog.sh, test/integration/test_query.sh, test/integration/test_schema_create.sh, test/integration/test_skv_client.sh
This allows a mix of checksum and non-checksum endpoints to still communicate with each-other
=> validate checksum only if present

src/k2/dto/K23SI.h, src/k2/module/k23si/client/k23si_client.cpp, src/k2/module/k23si/client/k23si_client.h, test/k23si/SKVClientTest.cpp
This is to support rowID for SQL and allow more efficient operations when the key can be reused to avoid extra serialization.
=> Add dto::Key interface to SKV client

src/k2/module/k23si/TxnManager.cpp, test/integration/heartbeat.sh, test/k23si/CMakeLists.txt, test/k23si/HeartbeatTest.cpp
The heartbeat.sh test failed 4 times in a row before the TxnManager heartbeat clock fix. Instrumentation showed  that the client was sending the heartbeat on time and it got a response from the server in under 100usec, so the problem was not overloading the network or future scheduling. After the TxnManager clock fix the test passed 4 times in a row.
=> Heartbeat fix

src/k2/dto/K23SI.h, src/k2/dto/K23SIInspect.h, src/k2/module/k23si/Module.cpp, src/k2/module/k23si/Module.h, src/k2/module/k23si/client/k23si_client.cpp, test/k23si/3SITxnTest.cpp, test/k23si/K23SITest.cpp
Makes write ops idempotent, which fixes failures on rejectIfExist=true retries. Also refactors DataRecord to split committed records from write intents, and removes unnecessary data from committed records. Closes #116
=> Idempotent write ops and DataRecord refactor

src/k2/cmd/tpcc/transactions.h
1) changed origin run() as attempt()
2) added retry strategy to try for a number of attempts.
3) tpcc integration tests succeeded
./test_k23si_tpcc.sh
>>>> Test ./test_k23si_tpcc.sh finished with code 0
=> retry failed transcations in TPCC benchmark tests

cluster/configs/tpcc_client.cfg, cluster/configs/tpcc_load.cfg, src/k2/cmd/tpcc/README, src/k2/cmd/tpcc/tpcc_client.cpp, test/integration/test_k23si_tpcc.sh
Introduced an option --txn_weights for tpcc client, for example,
./build/src/k2/cmd/tpcc/tpcc_client -c1 --tcp_remotes ${EPS} --cpo ${CPO} --tso_endpoint ${TSO} --num_warehouses ${NUMWH} --districts_per_warehouse ${NUMDIST} --prometheus_port 63101 ${COMMON_ARGS} --memory=512M --partition_request_timeout=1s  --num_concurrent_txns=1 --do_verification false --delivery_txn_batch_size=10 --txn_weights={43,4,4,45,4}
Updated integration test script and doc. 
TPCC integration tests passed.
>>>> Test ./test_k23si_tpcc.sh finished with code 0
=> add transaction weights to TPCC client

src/k2/cmd/tpcc/datagen.h, src/k2/cmd/tpcc/schema.h, src/k2/cmd/tpcc/tpcc_client.cpp, src/k2/module/k23si/client/k23si_client.cpp
- Fix query prefix scan bug that caused many extra records to be returned when there are both partition and range keys. This fixed the TPC-C performance bug.
- Add command line options to support TPC-C with multiple client instances
- Fix unsafe use after move in TPC-C data load
- Remove unneeded first name field from TPC-C customer secondary index
Tested with 4 server cores, 2 client instances with 2 client cores: 10,000 txns/sec with payment and new order txn types.
=> Fix query prefix scan bug plus TPC-C fixes

src/k2/cmd/ycsb/data.h, src/k2/cmd/ycsb/transactions.h
Resolved the issue of WI=0 in metrics.
Caused due to incorrect key formed while performing partial updates.
Used _num_fields instead of _field_length while creating keys.
=> Update operation issue due to _field_length in YCSB

src/k2/appbase/Appbase.h, src/k2/cmd/txbench/rpcbench_common.h, src/k2/common/Common.h, src/k2/cpo/service/CPOService.cpp, src/k2/dto/Expression.h, src/k2/dto/SKVRecord.cpp, src/k2/infrastructure/APIServer.cpp, src/k2/module/k23si/Module.cpp, src/k2/persistence/logStream/LogStream.cpp, src/k2/persistence/plog_service/PlogServer.h, src/k2/transport/Payload.cpp, src/k2/transport/Payload.h, src/k2/transport/RPCDispatcher.cpp, src/k2/transport/TXEndpoint.cpp, src/k2/transport/TXEndpoint.h, src/k2/transport/VirtualNetworkStack.cpp, src/k2/transport/VirtualNetworkStack.h, test/k23si/SKVRecordTest.cpp, test/plog/LogStreamTest.cpp, test/plog/PlogClientTest.cpp, test/transport/PayloadTest.cpp
Change to use a BinaryAllocator to replace the original BinaryAllocatorFunctor due to the following reasons:
1) holds a default block size, which the function could not have such a state
2) provide a method to allocate by a specific size instead of the default block size
All unit tests and integration tests passed.
root@b0d49a77c3ce:/build# cd build/test && ctest
Test project /build/build/test
Start 1: plogmock
1/9 Test #1: plogmock .........................   Passed    0.38 sec
Start 2: persistent_volume
2/9 Test #2: persistent_volume ................   Passed    3.09 sec
Start 3: transport
3/9 Test #3: transport ........................   Passed    0.09 sec
Start 4: readcache
4/9 Test #4: readcache ........................   Passed    0.03 sec
Start 5: skv_record
5/9 Test #5: skv_record …
=> change to use BinaryAllocator to replace BinaryAllocatorFunctor

src/k2/cmd/controlPlaneOracle/cpo_main.cpp, src/k2/cmd/nodepool/nodepool_main.cpp, src/k2/cmd/persistence/CMakeLists.txt, src/k2/cmd/persistence/persistence_main.cpp, src/k2/cmd/tso/CMakeLists.txt, src/k2/cmd/tso/tso_main.cpp, src/k2/common/Timer.h, src/k2/cpo/client/Heartbeat.cpp, src/k2/cpo/client/Heartbeat.h, src/k2/cpo/service/CPOService.cpp, src/k2/cpo/service/CPOService.h, src/k2/cpo/service/HealthMonitor.cpp, src/k2/cpo/service/HealthMonitor.h, src/k2/dto/ControlPlaneOracle.h, src/k2/dto/MessageVerbs.h, src/k2/module/k23si/Module.cpp, test/integration/heartbeat_monitor.py, test/integration/run.sh, test/integration/test_3si_txn.sh, test/integration/test_collection.sh, test/integration/test_heartbeat_monitor.sh, test/integration/test_k23si.sh, test/integration/test_k23si_tpcc.sh, test/integration/test_k23si_ycsb.sh, test/integration/test_query.sh, test/integration/test_schema_create.sh, test/integration/test_skv_client.sh
Implement health monitoring in the CPO via heartbeats. Failed components are reported in metrics and the log. The heartbeat responder is implemented as an applet and added to the nodepool, tso, and persistence. The nodepool will respond to requests with a 410 error if the heartbeat responder is not getting heartbeats from the CPO.
Tested on integration and unit tests, and added a simple integration test that kills the nodepool and verifies the metrics in the CPO.
=> Health monitor

src/k2/cmd/nodepool/nodepool_main.cpp, src/k2/module/k23si/Config.h, src/k2/module/k23si/Module.cpp, src/k2/module/k23si/Module.h
The bug was found by Jepsen tests. This PR is to only allow the push count for a key to be at most k23si_max_push_count, which is 1 by default.
=> do not allow infinite push for read and write operations

src/k2/cmd/tpcc/schema.h, src/k2/cmd/tpcc/tpcc_client.cpp, src/k2/cmd/tpcc/transactions.h, src/k2/cmd/tpcc/verify.cpp, src/k2/module/k23si/Module.cpp, src/k2/tso/client/Client.cpp, test/integration/test_k23si_tpcc.sh
Due to the range partitioning and key definition from the tpc-c spec, previously all of the tpc-c item rows were on a single partition that also owned the data for a tpc-c warehouse. The item table is heavily used and this caused that node to be overloaded and slow down the whole system's throughput (one symptom was the RDMA rx batch size was always maxed on that node).
This change puts the item table on a separate hash collection on a configurable number of nodes. Results:
- All txn types. Before: **171** txns/sec/nodepool core. After: **205** txns/sec/nodepool/core
- 50/50 payment/new order txns. Before: **160** txns/sec/nodepool core. After **464** txns/sec/nodepool core
RDMA rx batch sizes are similar and under the max for all nodes now. Also, abort rates are 10x higher than before so …
=> Use hash collection for TPC-C item table

install_deps.sh
crc32c version higher than 1.1.0 would cause dynamic/static link issues for platform. Use the latest stable version 1.1.0 specific for platform.
=> use crc32c version 1.1.0 to avoid library link issues

src/k2/module/k23si/client/k23si_client.cpp, src/k2/module/k23si/client/k23si_client.h, test/k23si/SKVClientTest.cpp
The request id was not incremented in the same way for partial updates and normal writes,  which caused the nodepool idempotency/retry logic to trigger and writes could be ignored while still returning an OK status code.
=> Fix bug for partial updates and writes to same key in same txn

docs/design/FILTER_EXPRESSIONS.md, src/k2/cmd/tpcc/schema.h, src/k2/cmd/tpcc/transactions.h, src/k2/cmd/tpcc/verify.cpp, src/k2/cmd/tpcc/verify.h, src/k2/common/Common.h, src/k2/dto/FieldTypes.cpp, src/k2/dto/FieldTypes.h, src/k2/dto/SKVRecord.h, src/k2/transport/Payload.cpp, src/k2/transport/Payload.h, src/k2/transport/PayloadSerialization.h, src/logging/src/k2/logging/BoostDecimals.h, src/logging/src/k2/logging/Decimal.h, src/logging/src/k2/logging/FormattingUtils.h, src/skvhttpclient/src/skvhttp/common/Common.h, src/skvhttpclient/src/skvhttp/dto/FieldTypes.cpp, src/skvhttpclient/src/skvhttp/dto/FieldTypes.h, src/skvhttpclient/src/skvhttp/mpack/MPackSerialization.h, src/skvhttpclient/test/ExpressionTest.cpp, src/skvhttpclient/test/mpacktest.cpp, test/integration/skvclient.py, test/k23si/ExpressionTest.cpp, test/k23si/SKVSerTest.cpp, test/transport/PayloadTest.cpp
Using memcpy to directly write and read cpp_dec_float types.
Assert sizeof(cpp_dec_float_50) == 56 and sizeof(cpp_dec_float_100) == 80
when write the float types.
=> Change decimal library - using memcpy

docs/design/FILTER_EXPRESSIONS.md, src/k2/dto/Expression.cpp, src/k2/dto/FieldTypes.cpp, src/k2/dto/FieldTypes.h, src/k2/dto/SKVRecord.h, src/skvhttpclient/src/skvhttp/dto/Expression.cpp, src/skvhttpclient/src/skvhttp/dto/FieldTypes.cpp, src/skvhttpclient/src/skvhttp/dto/FieldTypes.h, test/k23si/KeyEncodingTest.cpp, test/k23si/QueryTest.cpp, test/k23si/SKVClientTest.cpp, test/k23si/SKVRecordTest.cpp
- Add unsigned integers types, uint16_t, uint32_t, and uint64_t.
- Unsigned integers can serve as key fields.
- Unsigned ints and signed ints are not comparable.
- Floats and (signed/unsigned) ints are not comparable.
- Add unsigned cases in KeyEncodingTest, QueryTest, SKVClientTest, SKVRecordTest.
=> Add unsigned integer types

test/integration/test_http_client.sh, test/integration/test_http_cpp_client.sh
Test fails in build machine with timeout error for drop collection but it succeeds in my local machine:
http://k2-bvu-10001.usrd.futurewei.com:8080/view/all/job/chogori-platform/674/execution/node/69/log/
```
2022-10-19 20:51:24,501 [DEBUG] (connectionpool) http://127.0.0.1:30000/ "POST /api/TxnEnd HTTP/1.1" 200 None
.2022-10-19 20:51:24,502 [DEBUG] (skvclient) calling http://127.0.0.1:30000/api/DropCollection with data [b'HTTPClient']
[0153:20:34:53.859.871]-cpo_main-[0]-(k2::cpo_service) [Info] [/build/src/k2/cpo/service/Service.cpp:407 @handleCollectionDrop] Received collection drop request for HTTPClient
[0153:20:34:53.859.985]-cpo_main-[0]-(k2::cpo_service) [Info] [/build/src/k2/cpo/service/Service.cpp:717 @_getCollection] Found collection in: …
```
=> Increase cpo timeout

src/k2/cmd/ycsb/data.h, src/k2/tso/service/Clock.h, test/k23si/3SITxnTest.cpp
- Remove leftover include of gnu decimal library
- Remove x86 guard around the tso poller synchronization. The spinlock should ensure correctness on ARM as well
- Fix some unspecified execution order bugs in 3si test
Integration and unit tests passing on Mac M1
=> Fixes for ARM support

docs/perf/README.md
Using a better method to read YCSB szipfian performance results.
For all YCSB szipfian performance metrics, add the 4 minute average
curve (4m average) over the previous metrics.
The results are read on the 4m average curve at the time when the
performance *starts* to drop sharply in the last minute of the test run.
Using the same method, different people at different time will read
almost the same results. Thus, these performance results are now both
representative and comparable.
=> add performance results for all six tests
