futurewei-cloud/chogori-platform

docs/PERFORMANCE.md
src/k2/cmd/tpcc/schema.h
src/k2/cmd/tpcc/tpcc_client.cpp
src/k2/cpo/client/CPOClient.h
src/k2/cpo/service/CPOService.cpp
src/k2/dto/Collection.cpp
src/k2/dto/ControlPlaneOracle.h
src/k2/module/k23si/client/k23si_client.cpp
src/k2/module/k23si/client/k23si_client.h
test/cpo/CPOTest.cpp
test/k23si/K23SITest.cpp

Implement manual pre-split range partitioning feature. Update TPC-C test to use it and add performance results

Range partitioning

---

src/k2/dto/K23SIInspect.h
src/k2/dto/MessageVerbs.h
src/k2/module/k23si/Module.cpp
src/k2/module/k23si/Module.h
src/k2/module/k23si/TxnManager.cpp
src/k2/module/k23si/TxnManager.h
test/k23si/K23SITest.cpp

New inspection RPCs to facilitate tests and correctness tools. Augment tests with new RPCs.

K23SI Correctness

---

src/k2/cmd/tpcc/schema.h
src/k2/cmd/tpcc/tpcc_client.cpp
src/k2/cmd/txbench/k23sibench_client.cpp
src/k2/dto/SKVRecord.cpp
src/k2/dto/SKVRecord.h
src/k2/module/k23si/client/k23si_client.cpp
src/k2/module/k23si/client/k23si_client.h
test/k23si/3SITxnTest.cpp
test/k23si/K23SITest.cpp
test/k23si/KeyEncodingTest.cpp
test/k23si/SKVClientTest.cpp
test/k23si/SKVRecordTest.cpp
test/k23si/SKVSerTest.cpp

Add createSchema to SKV client
Minor refactor of SKV client
Tested with TPC-C which showed no performance impact

Change SKV interface to use std::shared_ptr

---

docs/SKV.md
src/k2/module/k23si/client/k23si_client.cpp
src/k2/module/k23si/client/k23si_client.h
test/k23si/SKVClientTest.cpp

prevent ops after end request. fixes #46

Prevent concurrent read or write with end request in SKV client and

---

.gitignore
src/k2/cmd/tpcc/tpcc_client.cpp
src/k2/common/Log.h
src/k2/cpo/client/CPOClient.h
src/k2/dto/Collection.h
src/k2/dto/ControlPlaneOracle.h
src/k2/dto/FieldTypes.h
src/k2/dto/K23SI.h
src/k2/module/k23si/client/k23si_client.cpp
src/k2/module/k23si/client/k23si_client.h
src/k2/transport/TXEndpoint.h
test/integration/run.sh
test/integration/test_3si_txn.sh
test/integration/test_schema_create.sh
test/k23si/3SITxnTest.cpp
test/k23si/K23SITest.cpp
test/k23si/SKVClientTest.cpp
test/k23si/SchemaCreationTest.cpp

- schema API now returns result objects to match the rest
- added std::hash for MTRs so that they can be used in hashmaps
- cleaned up std::cout in tests
- added assertions to SKV Schema test cases

client library interface enhancements

---

src/k2/cmd/nodepool/nodepool_main.cpp
src/k2/dto/Collection.h
src/k2/dto/K23SI.h
src/k2/dto/MessageVerbs.h
src/k2/dto/SKVRecord.cpp
src/k2/dto/SKVRecord.h
src/k2/module/k23si/Config.h
src/k2/module/k23si/Module.cpp
src/k2/module/k23si/Module.h
src/k2/module/k23si/client/k23si_client.cpp
src/k2/module/k23si/client/k23si_client.h
src/k2/module/k23si/client/query.cpp
src/k2/module/k23si/client/query.h
test/integration/run.sh
test/integration/test_query.sh
test/k23si/CMakeLists.txt
test/k23si/QueryTest.cpp
test/k23si/SKVClientTest.cpp
test/k23si/SKVSerTest.cpp

Implements read-only range scan for SKV. Does not support projection, filtering, or reverse direction yet

Basic SKV Query implementation

---

src/k2/cmd/tpcc/schema.h
src/k2/cmd/tpcc/tpcc_client.cpp
src/k2/cmd/tpcc/transactions.h
src/k2/dto/FieldTypes.cpp
src/k2/dto/FieldTypes.h
src/k2/dto/SKVRecord.h
src/k2/module/k23si/Module.cpp
test/cpo/CPOTest.cpp
test/k23si/KeyEncodingTest.cpp
test/k23si/SKVClientTest.cpp
test/k23si/SKVRecordTest.cpp
test/k23si/SKVSerTest.cpp
test/k23si/SchemaCreationTest.cpp

Support for SKV signed int key types, remove support for unsigned types

---

src/k2/dto/Collection.h
src/k2/dto/ControlPlaneOracle.cpp
src/k2/dto/ControlPlaneOracle.h
src/k2/dto/FieldTypes.cpp
src/k2/dto/FieldTypes.h
src/k2/dto/K23SI.h
src/k2/dto/MessageVerbs.h
src/k2/dto/SKVRecord.cpp
src/k2/dto/SKVRecord.h
src/k2/module/k23si/Module.cpp
src/k2/module/k23si/Module.h
src/k2/module/k23si/client/k23si_client.cpp
src/k2/module/k23si/client/k23si_client.h
test/k23si/3SITxnTest.cpp
test/k23si/K23SITest.cpp
test/k23si/SKVClientTest.cpp
test/k23si/SKVRecordTest.cpp
test/k23si/SKVSerTest.cpp

- Combine write and partial update into single RPC
- Fix exception throwing
- Fixes #1 
- Closes #63

SKV Code improvements

---

src/k2/dto/Expression.cpp
src/k2/dto/Expression.h
src/k2/dto/FieldTypes.h
src/k2/dto/SKVRecord.h
src/k2/module/k23si/Module.cpp
src/k2/module/k23si/Module.h

Also add license to Expression
Closes #70

Change Module.cpp to use cast apply macro

---

src/k2/module/k23si/Module.cpp
src/k2/module/k23si/Module.h
test/k23si/QueryTest.cpp

Add expression filter to SKV Query

---

src/k2/cmd/tpcc/schema.h
src/k2/cmd/tpcc/transactions.h
src/k2/cmd/tpcc/verify.h
src/k2/dto/FieldTypes.cpp
src/k2/dto/FieldTypes.h
src/k2/transport/Payload.cpp
src/k2/transport/Payload.h
test/integration/test_k23si_tpcc.sh

Add Decimal types to SKV and modify TPC-C to use them

---

src/k2/dto/K23SI.h
src/k2/module/k23si/Module.cpp
src/k2/module/k23si/client/k23si_client.cpp
src/k2/module/k23si/client/k23si_client.h
test/k23si/3SITxnTest.cpp
test/k23si/K23SITest.cpp
test/k23si/SKVClientTest.cpp

Implement rejectIfExists flag on SKV write to support SQL insert

---

docs/SKV.md
src/k2/dto/SKVRecord.cpp
src/k2/dto/SKVRecord.h
src/k2/module/k23si/Module.cpp
src/k2/module/k23si/client/k23si_client.cpp
src/k2/module/k23si/client/k23si_client.h
src/k2/module/k23si/client/query.cpp
src/k2/module/k23si/client/query.h
test/k23si/ExpressionTest.cpp
test/k23si/K23SITest.cpp
test/k23si/KeyEncodingTest.cpp
test/k23si/QueryTest.cpp
test/k23si/SKVClientTest.cpp
test/k23si/SKVSerTest.cpp

Also cleanup and tighten SKV interface

SkV getKey fix for returned records

---

src/k2/common/Common.h
src/k2/common/Log.h
src/k2/cpo/client/CPOClient.cpp
src/k2/dto/Expression.cpp
src/k2/dto/Expression.h

fix to_json  recursion on String
fix segv in CPO client
use less verbose function formatting in logs
fix bug in expression formatting

Expression fix

---

src/k2/common/Chrono.h
src/k2/common/Common.h
src/k2/dto/K23SI.h
src/k2/dto/SKVRecord.h
src/k2/module/k23si/Module.cpp
src/k2/module/k23si/Module.h
src/k2/module/k23si/client/k23si_client.h
src/k2/module/k23si/client/query.h

... And better errors in write request validation

Better formatting for various types

---

src/k2/module/k23si/client/query.h

Remove unused continuationToken field

---

src/k2/module/k23si/Module.cpp
src/k2/module/k23si/ReadCache.h

Still trying to repro the issue with this change.

Adding detailed log when w-r conflict on readcachey

---

src/k2/appbase/AppEssentials.h
src/k2/cmd/tpcc/tpcc_client.cpp
src/k2/cmd/tpcc/transactions.h
src/k2/cmd/txbench/CMakeLists.txt
src/k2/cmd/txbench/k23sibench_client.cpp
src/k2/cmd/txbench/rpcbench_client.cpp
src/k2/cmd/txbench/rpcbench_server.cpp
src/k2/cmd/txbench/txbench_client.cpp
src/k2/cmd/txbench/txbench_combine.cpp
src/k2/common/Chrono.h
src/k2/common/Common.h
src/k2/common/Log.h
src/k2/cpo/service/CPOService.cpp
src/k2/infrastructure/APIServer.cpp
src/k2/module/k23si/CMakeLists.txt
src/k2/module/k23si/Persistence.cpp
src/k2/module/k23si/client/CMakeLists.txt
src/k2/transport/RPCDispatcher.cpp
src/k2/transport/TCPRPCChannel.h
src/k2/transport/TCPRPCProtocol.cpp
src/k2/tso/service/TSOService.cpp
src/k2/tso/service/TSOWorker.cpp

matching PR for seastar master sync: 
https://github.com/futurewei-cloud/chogori-seastar-rd/pull/5

sync with seastar update

---

src/k2/dto/Expression.cpp
src/k2/dto/Expression.h
src/k2/module/k23si/client/query.h
src/k2/transport/Payload.cpp
src/k2/transport/Payload.h

Add copyPayloads to filter expression

Change Payload copy to use an allocating payload and write()

---

src/k2/dto/MessageVerbs.h
src/k2/tso/client/tso_clientlib.cpp
src/k2/tso/client/tso_clientlib.h
src/k2/tso/service/TSOController.cpp
src/k2/tso/service/TSOService.cpp
src/k2/tso/service/TSOService.h
src/k2/tso/service/TSOWorker.cpp

It may be easier to review by each commit.

Tso simplification

---

src/k2/module/k23si/Module.cpp

and fix bug where we might get rid of the wrong WI on a push response

fix race condition during push

---

src/k2/cmd/demo/rpc_service.cpp

- added not found key return on the server
- added test for the not found key

rpc demo fixes

---

src/k2/module/k23si/Module.cpp
test/k23si/QueryTest.cpp

Fixed reverse scan with no records issue.
Closes #169

Resolved Issue 169

---

src/k2/dto/Expression.h
src/k2/dto/FieldTypes.h
src/k2/dto/SKVRecord.h
test/k23si/ExpressionTest.cpp
test/k23si/SKVSerTest.cpp

Disallowed NaN for storage of float and double. 
Closes #170

Resolved Issue 170

---

src/k2/cmd/tpcc/schema.h
src/k2/cmd/tpcc/tpcc_client.cpp
src/k2/cmd/tpcc/transactions.h

Implemented Stock Level TPC-C Transaction
Closes #80

Stock level transaction

---

src/k2/cmd/tpcc/datagen.h
src/k2/cmd/tpcc/schema.h
src/k2/cmd/tpcc/tpcc_client.cpp
src/k2/cmd/tpcc/transactions.h

Implemented method getCIdByLastNameViaIndex() to replace getCIdByLastName().
TPCC integration tests succeeded.
>>>> Test ./test_k23si_tpcc.sh finished with code 0

add customer name secondary index to TPCC

---

src/k2/cmd/ycsb/README
src/k2/cmd/ycsb/data.h
src/k2/cmd/ycsb/dataload.h
src/k2/cmd/ycsb/transactions.h
src/k2/cmd/ycsb/ycsb_client.cpp
src/k2/cmd/ycsb/ycsb_rand.h
test/integration/test_k23si_ycsb.sh

Added all YCSB supported operations and key Distributions.

Transactions for YCSB

---

src/k2/cmd/ycsb/data.h
src/k2/cmd/ycsb/dataload.h
src/k2/cmd/ycsb/transactions.h

(i) Correct load phase - 
Problem:  created new random context for each batch of loads and thus each record was loaded with nearly prob=1.
Solution: made random context a data member of DataLoader class to ensure each record loads with prob=num_inserts/total_keys
(ii) Correct error code -
Problem: used 403 to catch record exists error.
Solution:  changed to 412 to catch precondition failed error which in turn captures record exists.

Minor changes to YCSB

---

src/k2/cmd/tpcc/datagen.h
src/k2/cmd/tpcc/schema.h
src/k2/cmd/tpcc/tpcc_client.cpp
src/k2/cmd/tpcc/transactions.h

Closed issue #220.
Added Secondary Index for Order to get Order Id using Customer Id.
Modified OrderStatus Transaction to use the secondary index.

Secondary index order

---

src/k2/module/k23si/Module.cpp
src/k2/module/k23si/Module.h

Added histograms for query scans and returns.

Query Metrics

---

cluster/TXDashboard.json
src/k2/cmd/httpclient/http_client.cpp
src/k2/cmd/nodepool/nodepool_main.cpp
src/k2/cmd/tpcc/tpcc_client.cpp
src/k2/cmd/ycsb/data.h
src/k2/cmd/ycsb/transactions.h
src/k2/cmd/ycsb/ycsb_client.cpp
src/k2/indexer/HOTIndexer.h
src/k2/module/k23si/Module.cpp
src/k2/module/k23si/Module.h
src/k2/module/k23si/Persistence.cpp
src/k2/module/k23si/Persistence.h
src/k2/module/k23si/ReadCache.h
src/k2/module/k23si/TxnManager.cpp
src/k2/module/k23si/TxnManager.h
src/k2/module/k23si/client/k23si_client.cpp
src/k2/module/k23si/client/k23si_client.h
src/k2/module/k23si/client/query.cpp
src/k2/transport/Prometheus.h
src/k2/tso/client/tso_clientlib.cpp
src/k2/tso/client/tso_clientlib.h
src/k2/tso/service/TSOController.cpp
src/k2/tso/service/TSOService.h
src/k2/tso/service/TSOWorker.cpp
test/k23si/3SITxnTest.cpp
test/k23si/K23SITest.cpp
test/k23si/SchemaCreationTest.cpp

cleanup global namespace
remove switch to disable metrics
remove redundant metric counter for latency metrics

Add metrics to TSO

---

src/k2/cmd/tpcc/datagen.h
src/k2/cmd/tpcc/schema.h
src/k2/cmd/tpcc/tpcc_client.cpp
src/k2/cmd/tpcc/transactions.h
src/k2/cmd/tpcc/verify.cpp
src/k2/cmd/tpcc/verify.h
test/integration/test_k23si_tpcc.sh

TPCC consistency verification tests implemented through test 9

TPCC verification tests

---

src/k2/cmd/httpclient/CMakeLists.txt

add http_client installation to cmake file.
Result for make install
-- Installing: /build/build/install/usr/local/bin/http_client

install http_client

---

src/k2/transport/AutoRRDMARPCProtocol.cpp
src/k2/transport/RPCDispatcher.cpp
src/k2/transport/RRDMARPCProtocol.cpp
src/k2/transport/TCPRPCProtocol.cpp
src/k2/transport/TXEndpoint.cpp
test/transport/CMakeLists.txt
test/transport/EndpointTest.cpp

fix endpoint parsing

---

src/k2/appbase/Appbase.cpp
src/k2/appbase/Appbase.h
src/k2/cmd/tpcc/datagen.h
src/k2/cmd/tpcc/dataload.h
src/k2/cmd/tpcc/schema.h
src/k2/cmd/tpcc/tpcc_client.cpp
src/k2/cmd/tpcc/transactions.h
src/k2/cmd/ycsb/data.h
src/k2/cmd/ycsb/dataload.h
src/k2/cmd/ycsb/transactions.h
src/k2/cmd/ycsb/ycsb_client.cpp
src/k2/cpo/service/HealthMonitor.h
src/k2/cpo/service/Service.cpp
src/k2/module/k23si/Module.cpp
src/k2/module/k23si/Persistence.cpp
test/cpo/CPOTest.cpp
test/dto/PartitionTest.cpp
test/integration/test_k23si_tpcc.sh
test/integration/test_k23si_ycsb.sh
test/k23si/3SITxnTest.cpp
test/k23si/K23SITest.cpp
test/k23si/QueryTest.cpp
test/k23si/SKVClientTest.cpp
test/k23si/SchemaCreationTest.cpp
test/plog/LogStreamTest.cpp
test/plog/PlogClientTest.cpp

* fix reactor stall in data generation
* remove sleep calls in favor for polling for completion

Distributed ycsb data loading

---

src/k2/cmd/nodepool/nodepool_main.cpp
src/k2/cmd/tpcc/tpcc_client.cpp
src/k2/cmd/tpcc/transactions.h
src/k2/cmd/txbench/k23sibench_client.cpp
src/k2/cmd/ycsb/data.h
src/k2/cmd/ycsb/ycsb_client.cpp
src/k2/cpo/client/Heartbeat.cpp
src/k2/cpo/service/Service.cpp
src/k2/transport/RRDMARPCChannel.cpp

- Fix TPC-C collection creation
- YCSB fixes for load phase
- Relax timeouts for CPO operations
- Remove soft-down from heartbeat check for now

Various fixes for benchmarks and remove soft-down from heartbeat check

---

src/k2/infrastructure/APIServer.cpp
src/k2/infrastructure/APIServer.h

To reduce compile time when some code is changed.

Move non template API Server methods to cpp file

---

src/k2/cmd/httpproxy/http_proxy_main.cpp
src/k2/dto/ControlPlaneOracle.h
src/k2/httpproxy/HTTPProxy.cpp
src/k2/httpproxy/HTTPProxy.h
src/k2/module/k23si/client/k23si_client.cpp
src/k2/module/k23si/client/k23si_client.h
test/integration/common_defs.sh
test/integration/skvclient.py
test/integration/test_http.py
test/integration/test_http_client.sh
test/k23si/SKVClientTest.cpp

https://github.com/futurewei-cloud/chogori-platform/issues/273

Create, get schema, and create collection by http proxy

---

src/k2/httpproxy/HTTPProxy.cpp
src/k2/httpproxy/HTTPProxy.h
test/integration/common_defs.sh
test/integration/skvclient.py
test/integration/test_http.py

https://github.com/futurewei-cloud/chogori-platform/issues/275

Implement Query Api by HTTP Proxy

---

src/k2/module/k23si/client/k23si_client.h

https://github.com/futurewei-cloud/chogori-platform/issues/212

Start client heartbeat timer in more cases

---

src/k2/cmd/nodepool/nodepool_main.cpp
src/k2/module/k23si/Config.h
src/k2/module/k23si/Module.cpp
src/k2/module/k23si/Module.h
test/integration/test_query.sh
test/k23si/QueryTest.cpp

https://github.com/futurewei-cloud/chogori-platform/issues/221

Add config to limit number of rows scanned during query

---

src/SKVClient/CMakeLists.txt
src/SKVClient/test/include/catch.hpp

CMake options for open gauss compatibility. Update Catch2 library for compatibility with newer glibc

SKVClient opengauss compatibility. Update Catch2

---

src/k2/httpproxy/HTTPProxy.cpp
src/k2/httpproxy/HTTPProxy.h
src/k2/module/k23si/client/k23si_client.h
src/skvhttpclient/src/skvhttp/common/Common.h
src/skvhttpclient/src/skvhttp/dto/Collection.cpp
src/skvhttpclient/src/skvhttp/dto/Collection.h
src/skvhttpclient/src/skvhttp/dto/ControlPlaneOracle.h
src/skvhttpclient/src/skvhttp/dto/K23SI.h
src/skvhttpclient/src/skvhttp/dto/SKVRecord.h
src/skvhttpclient/src/skvhttp/mpack/MPackSerialization.h
test/integration/skvclient.py
test/integration/test_http.py
test/integration/test_http_client.sh

This change implements the read/write paths in the python tester to make sure the HTTP proxy APIs are tested

implement data apis. add schema cache

---

CMakeLists.txt
README.md
install_deps.sh
src/k2/appbase/Appbase.cpp
src/k2/dto/Collection.h
src/k2/dto/K23SI.h
src/k2/module/k23si/Indexer.cpp
src/k2/module/k23si/client/k23si_client.cpp
src/logging/CMakeLists.txt
src/logging/src/k2/logging/FormattingUtils.h
src/logging/src/k2/logging/Log.h
src/skvhttpclient/CMakeLists.txt
src/skvhttpclient/src/skvhttp/client/SKVClient.h
src/skvhttpclient/test/ExpressionTest.cpp
src/skvhttpclient/test/SKVRecordTest.cpp
src/skvhttpclient/test/mpacktest.cpp
test/include/catch2/catch.hpp
test/integration/test_3si_txn.sh
test/integration/test_heartbeat_monitor.sh
test/integration/test_http_client.sh
test/integration/test_k23si.sh
test/integration/test_skv_client.sh
test/transport/EndpointTest.cpp

- Remove constructors from some dtos to allow and encourage named initializer list construction
- Renamed the LogLevel enum levels
- Updated catch dependency
- Updated open source install_deps.sh and README

Update for opengauss and compiler compatibility

---

src/skvhttpclient/src/skvhttp/client/SKVClient.cpp
src/skvhttpclient/src/skvhttp/client/SKVClient.h
src/skvhttpclient/src/skvhttp/common/Serialization.h
src/skvhttpclient/src/skvhttp/dto/ControlPlaneOracle.h
src/skvhttpclient/src/skvhttp/dto/SKVRecord.h
src/skvhttpclient/test/CMakeLists.txt
src/skvhttpclient/test/ClientIntegrationTest.cpp
src/skvhttpclient/test/mpacktest.cpp
test/integration/test_http_cpp_client.sh

Query and partial update are still unimplemented

Implement basic operations in skvhttp client. 

---

src/skvhttpclient/src/skvhttp/dto/SKVRecord.h

fix potential issue of making a call in an assert

reposition field cursor in skvrecord build

---

src/k2/cpo/service/Service.cpp
src/k2/dto/ControlPlaneOracle.h
src/k2/module/k23si/client/k23si_client.cpp
src/k2/module/k23si/client/k23si_client.h
src/k2/tso/client/Client.cpp
src/k2/tso/client/Client.h
test/integration/test_collection.sh

As mentioned in #295, replacing k23si client minimum transaction time to be using the error bound assignment value from CPO.

added k23si get minTransTime from TSO client

---

src/skvhttpclient/src/skvhttp/dto/SKVRecord.cpp
src/skvhttpclient/src/skvhttp/dto/SKVRecord.h

This will make a cleaner interface for usage in chogori-opengauss

Add getters for schema and collectionName in SKVRecordBuilder

---

src/k2/httpproxy/HTTPProxy.cpp
src/k2/httpproxy/HTTPProxy.h
src/k2/module/k23si/client/query.cpp
src/k2/module/k23si/client/query.h
src/skvhttpclient/src/skvhttp/client/SKVClient.cpp
src/skvhttpclient/src/skvhttp/client/SKVClient.h
src/skvhttpclient/src/skvhttp/dto/K23SI.h
src/skvhttpclient/test/ClientIntegrationTest.cpp
test/integration/skvclient.py

Fix for query retry and pagination in skvhttp client

---

src/k2/dto/MessageVerbs.h
src/k2/dto/TSO.h
src/k2/tso/client/Client.cpp
src/k2/tso/client/Client.h
src/k2/tso/service/Service.cpp
src/k2/tso/service/Service.h

Use _doGetTSOEndpoints() in the TSO client to set all the TSO endpoints.

use _doGetTSOEndpoints() to set all tso endpoints

---

src/skvhttpclient/src/skvhttp/dto/Collection.h
src/skvhttpclient/src/skvhttp/dto/SKVRecord.h
test/integration/CMakeLists.txt
test/integration/run_k2_cluster.sh

[make runner script install executable]
[fix shutdown in run_k2_cluster]
[fix logging of keys in skvclient]

Make runner script executable

---

src/k2/httpproxy/HTTPProxy.cpp
src/k2/module/k23si/Module.cpp

issue txn abort from proxy when txns are abandoned

Fix push count limit for query
